package com.project.project.util;

import java.util.UUID;

/**
 * Utility class for generating unique IDs.
 * The ID is generated by concatenating the entity name with a random UUID.
 */
public class IdGenerator {

    /**
     * Generates a unique ID for the given entity.
     *
     * @param entity The name of the entity for which the ID is being generated.
     * @return A unique ID string.
     */
    public static String generateId(String entity) {
        return entity + UUID.randomUUID().toString();
    }
}
