package com.project.project.service.security;

import lombok.Data;

/**
 * This class represents a login request containing the user's nickname, captcha, and captcha key.
 * It is used to transfer login data from the client to the server.
 */
@Data
public class LoginRequest {

    /**
     * The nickname of the user attempting to log in.
     */
    private String nickName;

    /**
     * The captcha input provided by the user.
     */
    private String captcha;

    /**
     * The key associated with the captcha for validation.
     */
    private String captchaKey;

    // Getters and Setters generated by Lombok's @Data annotation
}
